name: gym_daily
description: "The gym daily app should contain sets of exercises for each day."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # localization
  slang: 4.4.0
  slang_flutter: 4.4.0
  flutter_localizations:
    sdk: flutter

  # state management / di
  hooks_riverpod: 2.6.1
  flutter_hooks: 0.20.5
  riverpod_annotation: 2.6.1

  # ui
  cupertino_icons: 1.0.2
  flex_color_scheme: 8.0.2
  lottie: 3.3.0
  formz: 0.8.0
  form_validator: 2.1.1
  flutter_svg: 2.0.16
  toastification: 2.3.0
  syncfusion_flutter_datepicker: 28.2.4

  # network
  firebase_core: 2.27.1
  firebase_auth: 4.17.9

  # navigation
  go_router: 14.6.2

  # assets
  flutter_gen: 5.8.0

  # entities generation
  freezed: 2.5.7
  freezed_annotation: 2.4.4

  # logger
  logger: 2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code gen
  riverpod_generator: 2.6.3
  build_runner: 2.4.14
  go_router_builder: 2.7.1
  slang_build_runner: 4.4.0
  flutter_gen_runner: 5.8.0

  # lints
  custom_lint: 0.7.0
  riverpod_lint: 2.6.3
  very_good_analysis: 7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/

flutter_gen:
  output: lib/src/resources
  line_length: 80

